retry yarn-container-logs as app owner

diff --git a/yarn-container-logs b/yarn-container-logs
--- a/yarn-container-logs
+++ b/yarn-container-logs
@@ -25,7 +25,30 @@ if [ -s "$cached_log_file" ]; then
   split-yarn-logs-per-container "$cached_log_file"
 else
   echo "Downloading logs for $appid and splitting per-container..."
-  yarn logs -applicationId "$appid" | split-yarn-logs-per-container
+
+  logfile="$(mktemp)"
+  rmtmp() {
+    rm -f "$logfile"
+  }
+  trap rmtmp EXIT
+
+  if ! yarn logs -applicationId "$appid" > "$logfile"; then
+    if [ -n "$YARN_LOGS_USER" ]; then
+      echo "Caught error; fetching owner..."
+      owner="$(yarn application -list -appStates FINISHED | grep "$appid" | awk '{ print $4 }')"
+      if [ -n "$owner" ]; then
+        echo "Found app owner: $owner; retrying fetching logs for $appid as user $YARN_LOGS_USER..."
+        sudo -u "$YARN_LOGS_USER" yarn logs -applicationId "$appid" -appOwner "$owner" > "$logfile"
+      else
+        echo "Unable to find application $appid" 1>&2
+        exit 1
+      fi
+    else
+      echo "Failed to fetch YARN logs; if this app was run by a user other than you, consider setting \$YARN_LOGS_USER and trying again." 1>&2
+      exit 1
+    fi
+  fi
+  cat "$logfile" | split-yarn-logs-per-container
 fi
 
 cd "$dest_dir"
